// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Feed struct {
	ID            uuid.UUID
	Createdat     time.Time
	Updatedat     time.Time
	Name          string
	Url           string
	Userid        uuid.UUID
	Lastfetchedat sql.NullTime
}

type FeedFollow struct {
	ID        uuid.UUID
	Createdat time.Time
	Updatedat time.Time
	Userid    uuid.UUID
	Feedid    uuid.UUID
}

type Post struct {
	ID          uuid.UUID
	Createdat   time.Time
	Updatedat   time.Time
	Title       string
	Description sql.NullString
	Url         string
	Feedid      uuid.UUID
	Publishedat time.Time
}

type User struct {
	ID        uuid.UUID
	Createdat time.Time
	Updatedat time.Time
	Name      string
	ApiKey    string
}
